- hosts: all
  become: yes
  tasks:
   - name: Add Docker YUM repository
     shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  
   - name: add Kubernetes YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes Repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/apt/doc/yum-key.gpg
      state: present

   - name: install kubelet
     yum:
      name: kubelet
      state: present
      update_cache: true

   - name: install docker-ce
     yum:
      name: docker-ce-3:18.09.1-3.el7
      state: present

   - name: install kubeadm
     yum:
      name: kubeadm
      state: present

   - name: Create Dockeretc Directory
     file:
      path: /etc/docker
      state: directory

   - name: Create docker.service.d Directory
     file:
      path: /etc/systemd/system/docker.service.d
      state: directory

   - name: Copy daemon.json file
     copy:
      src: /tmp/daemon.json
      dest: /etc/docker/daemon.json

   - name: Enable Docker service
     systemd:
      state: started
      enabled: yes
      name: docker

   - name: Enable Kubelet service
     systemd:
      state: started
      enabled: yes
      name: kubelet

   - name: Disable Firewalld service
     systemd:
      state: stopped
      enabled: no
      name: firewalld

   - name: Add a line to a file if the file does not exist, without passing regexp
     lineinfile:
      path: /etc/sysctl.conf
      line: vm.swappiness = 0

   - name: Ejecutar sysctl
     shell: sysctl -p
  
   - name: Bajar Swap
     shell: swapoff -a
    
- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
       name: kubectl
       state: present